package BACnetCore.Enums;

/**
 * Created by Phil on 3/20/2016.
 */
public enum BacnetRejectReasons {

    REJECT_REASON_OTHER (0),
    REJECT_REASON_BUFFER_OVERFLOW (1),
    REJECT_REASON_INCONSISTENT_PARAMETERS (2),
    REJECT_REASON_INVALID_PARAMETER_DATA_TYPE (3),
    REJECT_REASON_INVALID_TAG (4),
    REJECT_REASON_MISSING_REQUIRED_PARAMETERS (5),
    REJECT_REASON_PARAMETER_OUT_OF_RANGE (6),
    REJECT_REASON_TOO_MANY_ARGUMENTS (7),
    REJECT_REASON_UNDEFINED_ENUMERATION (8),
    REJECT_REASON_UNRECOGNIZED_SERVICE (9),
    MAX_BACNET_REJECT_REASON (10),
    REJECT_REASON_PROPRIETARY_FIRST (64),
    REJECT_REASON_PROPRIETARY_LAST (65535);

    private int flags;

    private BacnetRejectReasons(int flags){
        this.flags = flags;
    }
}
